[package]
name = "bevy"
version = "0.1.0"
description = "Bevy example"
license = "MIT"
edition = "2021"
exclude = ["index.node"]

[workspace]
resolver = "2"

[lib]
crate-type = ["cdylib"]

[dependencies]
bevy = "0.9"
bevy_embedded_assets = "0.6"

[dependencies.neon]
version = "0.10.1"
default-features = false
features = ["napi-6"]
